<?php

$apiKey="rzp_test_pEfOhv6EwloaIq";	
session_start();
include('dbcon.php');
$db=new dbcon;
$pic=$_SESSION['pickLoc'];
$dest=$_SESSION['avlStation'];
$trmo=$_SESSION['transMode'];
$sql="select * from ratecalc where pickLoc='$pic' AND avlStation='$dest' AND transMode='$trmo'";
$query=$db->selectData($sql);
if($row=mysqli_fetch_array($query))
{
    $rate=$row['rate']*100; ?>
?>

<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $rate; ?>"// Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'ORD'.rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Metro By vehicles"
    data-description="Payment Portal"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name=""
    data-prefill.email=""
    data-prefill.contact=""
    data-theme.color="#f0d4dc"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>